[package]
name = "memlayout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.4"
image = "0.23.0"
plotters = "0.3"
egui = "0.15.0"
egui_glium = "0.15.0"
glium = "0.29.0"
